openapi: 3.1.0

info:
  title: Common schema definitions
  version: 0.0.0
  description: >-
    This file contains component definitions used by multiple components

components:
  schemas:

    Common.ResponseSuccess:
      type: object
      properties:
        message:
          type: string
          x-field-uid: 1
    Error:
      description: |-
        Error response generated while serving API request.
      type: object
      required:
      - code
      - errors
      properties:
        code:
           description: |-
             Numeric status code based on underlying transport being used.
           type: integer
           x-field-uid: 1
        kind:
          description: |-
            Kind of error message.
          type: string
          x-enum:
            transport:
              x-field-uid: 1
            validation:
              x-field-uid: 2
            internal:
              x-field-uid: 3
          x-field-uid: 2
          enum:
          - transport
          - validation
          - internal
        errors:
          description: |-
            List of error messages generated while serving API request.
          type: array
          items:
            type: string
          x-field-uid: 3
