openapi: 3.0.3

info:
  title: Schema for ServiceAbc
  version: 0.0.0
  description: >-

paths:

  /serviceb:
    get:
      tags: [ServiceAbc]
      operationId: GetAllItems
      description: return list of some items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './service_b.yaml#/components/schemas/ServiceAbc.ItemList'
          x-field-uid: 1
        default:
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Error'
          x-field-uid: 2
  /serviceb/{item_id}:
    get:
      tags: [ServiceAbc]
      operationId: GetSingleItem
      description: return single item
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './service_b.yaml#/components/schemas/ServiceAbc.Item'
          x-field-uid: 1
        default:
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Error'
          x-field-uid: 2
  /serviceb/{item_id}/{level_2}:
    get:
      tags: [ServiceAbc]
      # operationId will be CamelCased, it is not possible to define a private method in an interface
      operationId: getSingleItemLevel2
      description: return single item
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: string
        - in: path
          name: level_2
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './service_b.yaml#/components/schemas/ServiceAbc.Item'
          x-field-uid: 1
        default:
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Error'
          x-field-uid: 2
