openapi: 3.1.0

info:
  title: Service-B components
  version: 0.0.0

components:
  schemas:

    ServiceAbc.Item:
      type: object
      properties:
        some_id:
          type: string
          x-field-uid: 1
        some_string:
          type: string
          x-field-uid: 2
        path_id:
          type: string
          x-field-uid: 3
        level_2:
          type: string
          x-field-uid: 4
    ServiceAbc.ItemList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ServiceAbc.Item'
          x-field-uid: 1
