// This file is autogenerated. Do not modify
package controllers

import (
	"net/http"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi/interfaces"
)

type apiTestController struct {
	handler interfaces.ApiTestHandler
}

func NewHttpApiTestController(handler interfaces.ApiTestHandler) interfaces.ApiTestController {
	return &apiTestController{handler}
}

func (ctrl *apiTestController) Routes() []httpapi.Route {
	return [] httpapi.Route {
		{ Path: "/apitest", Method: "GET", Name: "GetRootResponse", Handler: ctrl.GetRootResponse},
		{ Path: "/apitest", Method: "POST", Name: "PostRootResponse", Handler: ctrl.PostRootResponse},
	}
}

/*
GetRootResponse: GET /apitest
Description: simple GET api with single return type
*/
func (ctrl *apiTestController) GetRootResponse(w http.ResponseWriter, r *http.Request) {
	result := ctrl.handler.GetRootResponse(r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

/*
PostRootResponse: POST /apitest
Description: simple POST api with single return type
*/
func (ctrl *apiTestController) PostRootResponse(w http.ResponseWriter, r *http.Request) {
	result := ctrl.handler.PostRootResponse(r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

