// This file is autogenerated. Do not modify
package controllers

import (
	"net/http"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi/interfaces"
)

type serviceBController struct {
	handler interfaces.ServiceBHandler
}

func NewHttpServiceBController(handler interfaces.ServiceBHandler) interfaces.ServiceBController {
	return &serviceBController{handler}
}

func (ctrl *serviceBController) Routes() []httpapi.Route {
	return [] httpapi.Route {
		{ Path: "/serviceb", Method: "GET", Name: "GetAllItems", Handler: ctrl.GetAllItems},
		{ Path: "/serviceb/{item_id}", Method: "GET", Name: "GetSingleItem", Handler: ctrl.GetSingleItem},
		{ Path: "/serviceb/{item_id}/{level_2}", Method: "GET", Name: "GetSingleItemLevel2", Handler: ctrl.GetSingleItemLevel2},
	}
}

/*
GetAllItems: GET /serviceb
Description: return list of some items
*/
func (ctrl *serviceBController) GetAllItems(w http.ResponseWriter, r *http.Request) {
	result := ctrl.handler.GetAllItems(r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

/*
GetSingleItem: GET /serviceb/{item_id}
Description: return single item
*/
func (ctrl *serviceBController) GetSingleItem(w http.ResponseWriter, r *http.Request) {
	result := ctrl.handler.GetSingleItem(r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

/*
GetSingleItemLevel2: GET /serviceb/{item_id}/{level_2}
Description: return single item
*/
func (ctrl *serviceBController) GetSingleItemLevel2(w http.ResponseWriter, r *http.Request) {
	result := ctrl.handler.GetSingleItemLevel2(r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

