// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	openapiart "github.com/open-traffic-generator/openapiart/pkg"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
)

type ApiTestController interface {
	Routes() []httpapi.Route
	GetRootResponse(w http.ResponseWriter, r *http.Request)
	DummyResponseTest(w http.ResponseWriter, r *http.Request)
	PostRootResponse(w http.ResponseWriter, r *http.Request)
}

type ApiTestHandler interface {
	GetController() ApiTestController
	/*
		GetRootResponse: GET /api/apitest
		Description: simple GET api with single return type
	*/
	GetRootResponse(r *http.Request) (openapiart.GetRootResponseResponse, error)
	/*
		DummyResponseTest: DELETE /api/apitest
		Description:
	*/
	DummyResponseTest(r *http.Request) (openapiart.DummyResponseTestResponse, error)
	/*
		PostRootResponse: POST /api/apitest
		Description: simple POST api with single return type
	*/
	PostRootResponse(rbody openapiart.ApiTestInputBody, r *http.Request) (openapiart.PostRootResponseResponse, error)
}
