// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	openapiart "github.com/open-traffic-generator/openapiart/pkg"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
)

type CapabilitiesController interface {
	Routes() []httpapi.Route
	GetVersion(w http.ResponseWriter, r *http.Request)
}

type CapabilitiesHandler interface {
	GetController() CapabilitiesController
	/*
		GetVersion: GET /api/capabilities/version
		Description:
	*/
	GetVersion(r *http.Request) (openapiart.GetVersionResponse, error)
}
