// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	openapiart "github.com/open-traffic-generator/openapiart/pkg"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
)

type MetricsController interface {
	Routes() []httpapi.Route
	GetMetrics(w http.ResponseWriter, r *http.Request)
	GetWarnings(w http.ResponseWriter, r *http.Request)
	ClearWarnings(w http.ResponseWriter, r *http.Request)
}

type MetricsHandler interface {
	GetController() MetricsController
	/*
		GetMetrics: GET /api/metrics
		Description: Gets metrics.
	*/
	GetMetrics(rbody openapiart.MetricsRequest, r *http.Request) (openapiart.GetMetricsResponse, error)
	/*
		GetWarnings: GET /api/warnings
		Description: Gets warnings.
	*/
	GetWarnings(r *http.Request) (openapiart.GetWarningsResponse, error)
	/*
		ClearWarnings: DELETE /api/warnings
		Description: Clears warnings.
	*/
	ClearWarnings(r *http.Request) (openapiart.ClearWarningsResponse, error)
}
