# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
try:
    import sanity_pb2 as sanity__pb2
except ImportError:
    from sanity import sanity_pb2 as sanity__pb2


class OpenapiStub(object):
    """Description missing in models

    For all RPCs defined in this service, API Server SHOULD provide JSON
    representation of `Error` message as an error string upon failure, ensuring
    name of enum constants (instead of value) for `kind` property is present
    in the representation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetConfig = channel.unary_unary(
                '/sanity.Openapi/SetConfig',
                request_serializer=sanity__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=sanity__pb2.SetConfigResponse.FromString,
                )
        self.UpdateConfiguration = channel.unary_unary(
                '/sanity.Openapi/UpdateConfiguration',
                request_serializer=sanity__pb2.UpdateConfigurationRequest.SerializeToString,
                response_deserializer=sanity__pb2.UpdateConfigurationResponse.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/sanity.Openapi/GetConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.GetConfigResponse.FromString,
                )
        self.GetMetrics = channel.unary_unary(
                '/sanity.Openapi/GetMetrics',
                request_serializer=sanity__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=sanity__pb2.GetMetricsResponse.FromString,
                )
        self.GetWarnings = channel.unary_unary(
                '/sanity.Openapi/GetWarnings',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.GetWarningsResponse.FromString,
                )
        self.ClearWarnings = channel.unary_unary(
                '/sanity.Openapi/ClearWarnings',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.ClearWarningsResponse.FromString,
                )
        self.GetRootResponse = channel.unary_unary(
                '/sanity.Openapi/GetRootResponse',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.GetRootResponseResponse.FromString,
                )
        self.DummyResponseTest = channel.unary_unary(
                '/sanity.Openapi/DummyResponseTest',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.DummyResponseTestResponse.FromString,
                )
        self.PostRootResponse = channel.unary_unary(
                '/sanity.Openapi/PostRootResponse',
                request_serializer=sanity__pb2.PostRootResponseRequest.SerializeToString,
                response_deserializer=sanity__pb2.PostRootResponseResponse.FromString,
                )
        self.GetAllItems = channel.unary_unary(
                '/sanity.Openapi/GetAllItems',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.GetAllItemsResponse.FromString,
                )
        self.GetSingleItem = channel.unary_unary(
                '/sanity.Openapi/GetSingleItem',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.GetSingleItemResponse.FromString,
                )
        self.GetSingleItemLevel2 = channel.unary_unary(
                '/sanity.Openapi/GetSingleItemLevel2',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.GetSingleItemLevel2Response.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/sanity.Openapi/GetVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sanity__pb2.GetVersionResponse.FromString,
                )


class OpenapiServicer(object):
    """Description missing in models

    For all RPCs defined in this service, API Server SHOULD provide JSON
    representation of `Error` message as an error string upon failure, ensuring
    name of enum constants (instead of value) for `kind` property is present
    in the representation
    """

    def SetConfig(self, request, context):
        """Sets configuration resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfiguration(self, request, context):
        """Deprecated: please use post instead

        Sets configuration resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Gets the configuration resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Gets metrics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWarnings(self, request, context):
        """Gets warnings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearWarnings(self, request, context):
        """Clears warnings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRootResponse(self, request, context):
        """simple GET api with single return type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DummyResponseTest(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostRootResponse(self, request, context):
        """simple POST api with single return type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllItems(self, request, context):
        """return list of some items
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingleItem(self, request, context):
        """return single item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingleItemLevel2(self, request, context):
        """return single item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenapiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=sanity__pb2.SetConfigRequest.FromString,
                    response_serializer=sanity__pb2.SetConfigResponse.SerializeToString,
            ),
            'UpdateConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfiguration,
                    request_deserializer=sanity__pb2.UpdateConfigurationRequest.FromString,
                    response_serializer=sanity__pb2.UpdateConfigurationResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.GetConfigResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=sanity__pb2.GetMetricsRequest.FromString,
                    response_serializer=sanity__pb2.GetMetricsResponse.SerializeToString,
            ),
            'GetWarnings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWarnings,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.GetWarningsResponse.SerializeToString,
            ),
            'ClearWarnings': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearWarnings,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.ClearWarningsResponse.SerializeToString,
            ),
            'GetRootResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRootResponse,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.GetRootResponseResponse.SerializeToString,
            ),
            'DummyResponseTest': grpc.unary_unary_rpc_method_handler(
                    servicer.DummyResponseTest,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.DummyResponseTestResponse.SerializeToString,
            ),
            'PostRootResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.PostRootResponse,
                    request_deserializer=sanity__pb2.PostRootResponseRequest.FromString,
                    response_serializer=sanity__pb2.PostRootResponseResponse.SerializeToString,
            ),
            'GetAllItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllItems,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.GetAllItemsResponse.SerializeToString,
            ),
            'GetSingleItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingleItem,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.GetSingleItemResponse.SerializeToString,
            ),
            'GetSingleItemLevel2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingleItemLevel2,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.GetSingleItemLevel2Response.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sanity__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sanity.Openapi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Openapi(object):
    """Description missing in models

    For all RPCs defined in this service, API Server SHOULD provide JSON
    representation of `Error` message as an error string upon failure, ensuring
    name of enum constants (instead of value) for `kind` property is present
    in the representation
    """

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/SetConfig',
            sanity__pb2.SetConfigRequest.SerializeToString,
            sanity__pb2.SetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/UpdateConfiguration',
            sanity__pb2.UpdateConfigurationRequest.SerializeToString,
            sanity__pb2.UpdateConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.GetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetMetrics',
            sanity__pb2.GetMetricsRequest.SerializeToString,
            sanity__pb2.GetMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWarnings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetWarnings',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.GetWarningsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearWarnings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/ClearWarnings',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.ClearWarningsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRootResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetRootResponse',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.GetRootResponseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DummyResponseTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/DummyResponseTest',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.DummyResponseTestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostRootResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/PostRootResponse',
            sanity__pb2.PostRootResponseRequest.SerializeToString,
            sanity__pb2.PostRootResponseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetAllItems',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.GetAllItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSingleItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetSingleItem',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.GetSingleItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSingleItemLevel2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetSingleItemLevel2',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.GetSingleItemLevel2Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanity.Openapi/GetVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sanity__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
