// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	openapi "github.com/open-traffic-generator/goapi/pkg"
	"github.com/open-traffic-generator/goapi/pkg/httpapi"
)

type ApiTestController interface {
	Routes() []httpapi.Route
	GetRootResponse(w http.ResponseWriter, r *http.Request)
	DummyResponseTest(w http.ResponseWriter, r *http.Request)
	PostRootResponse(w http.ResponseWriter, r *http.Request)
}

type ApiTestHandler interface {
	GetController() ApiTestController
	/*
		GetRootResponse: GET /api/apitest
		Description: simple GET api with single return type
	*/
	GetRootResponse(r *http.Request) (openapi.GetRootResponseResponse, error)
	/*
		DummyResponseTest: DELETE /api/apitest
		Description:
	*/
	DummyResponseTest(r *http.Request) (openapi.DummyResponseTestResponse, error)
	/*
		PostRootResponse: POST /api/apitest
		Description: simple POST api with single return type
	*/
	PostRootResponse(rbody openapi.ApiTestInputBody, r *http.Request) (openapi.PostRootResponseResponse, error)
}
