// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	openapi "github.com/open-traffic-generator/goapi/pkg"
	"github.com/open-traffic-generator/goapi/pkg/httpapi"
)

type CapabilitiesController interface {
	Routes() []httpapi.Route
	GetVersion(w http.ResponseWriter, r *http.Request)
}

type CapabilitiesHandler interface {
	GetController() CapabilitiesController
	/*
		GetVersion: GET /api/capabilities/version
		Description:
	*/
	GetVersion(r *http.Request) (openapi.GetVersionResponse, error)
}
