// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	openapi "github.com/open-traffic-generator/goapi/pkg"
	"github.com/open-traffic-generator/goapi/pkg/httpapi"
)

type UnitTestController interface {
	Routes() []httpapi.Route
	GetTestConfig(w http.ResponseWriter, r *http.Request)
	SetTestConfig(w http.ResponseWriter, r *http.Request)
}

type UnitTestHandler interface {
	GetController() UnitTestController
	/*
		GetTestConfig: GET /api/test
		Description: Get the new restructured unit test config.
	*/
	GetTestConfig(r *http.Request) (openapi.GetTestConfigResponse, error)
	/*
		SetTestConfig: POST /api/test
		Description: Sets the new restructured unit test configuration.
	*/
	SetTestConfig(rbody openapi.TestConfig, r *http.Request) (openapi.SetTestConfigResponse, error)
}
