// This file is autogenerated. Do not modify
package controllers

import (
	"errors"
	"io"
	"log"
	"net/http"

	openapi "github.com/open-traffic-generator/goapi/pkg"
	"github.com/open-traffic-generator/goapi/pkg/httpapi"
	"github.com/open-traffic-generator/goapi/pkg/httpapi/interfaces"
)

type bundlerController struct {
	handler interfaces.BundlerHandler
}

func NewHttpBundlerController(handler interfaces.BundlerHandler) interfaces.BundlerController {
	return &bundlerController{handler}
}

func (ctrl *bundlerController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/api/config", Method: "POST", Name: "SetConfig", Handler: ctrl.SetConfig},
		{Path: "/api/config", Method: "PATCH", Name: "UpdateConfiguration", Handler: ctrl.UpdateConfiguration},
		{Path: "/api/config", Method: "GET", Name: "GetConfig", Handler: ctrl.GetConfig},
	}
}

/*
SetConfig: POST /api/config
Description: Sets configuration resources.
*/
func (ctrl *bundlerController) SetConfig(w http.ResponseWriter, r *http.Request) {
	var item openapi.PrefixConfig
	if r.Body != nil {
		body, readError := io.ReadAll(r.Body)
		if body != nil {
			item = openapi.NewPrefixConfig()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSetConfigError(w, "validation", err)
				return
			}
		} else {
			ctrl.responseSetConfigError(w, "validation", readError)
			return
		}
	} else {
		bodyError := errors.New("Request does not have a body")
		ctrl.responseSetConfigError(w, "validation", bodyError)
		return
	}
	result, err := ctrl.handler.SetConfig(item, r)
	if err != nil {
		ctrl.responseSetConfigError(w, "internal", err)
		return
	}

	if result.HasResponseBytes() {
		if _, err := httpapi.WriteByteResponse(w, 200, result.ResponseBytes()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseSetConfigError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *bundlerController) responseSetConfigError(w http.ResponseWriter, errorKind openapi.ErrorKindEnum, rsp_err error) {
	var result openapi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(openapi.Error); ok {
		result = rErr
	} else {
		result = openapi.NewError()
		err := result.FromJson(rsp_err.Error())
		if err != nil {
			result.Msg().Code = statusCode
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			result.Msg().Errors = []string{rsp_err.Error()}
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result); err != nil {
		log.Print(err.Error())
	}
}

/*
UpdateConfiguration: PATCH /api/config
Description: Deprecated: please use post instead

Sets configuration resources.
*/
func (ctrl *bundlerController) UpdateConfiguration(w http.ResponseWriter, r *http.Request) {
	var item openapi.UpdateConfig
	if r.Body != nil {
		body, readError := io.ReadAll(r.Body)
		if body != nil {
			item = openapi.NewUpdateConfig()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseUpdateConfigurationError(w, "validation", err)
				return
			}
		} else {
			ctrl.responseUpdateConfigurationError(w, "validation", readError)
			return
		}
	} else {
		bodyError := errors.New("Request does not have a body")
		ctrl.responseUpdateConfigurationError(w, "validation", bodyError)
		return
	}
	result, err := ctrl.handler.UpdateConfiguration(item, r)
	if err != nil {
		ctrl.responseUpdateConfigurationError(w, "internal", err)
		return
	}

	if result.HasPrefixConfig() {
		if _, err := httpapi.WriteJSONResponse(w, 200, result.PrefixConfig()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseUpdateConfigurationError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *bundlerController) responseUpdateConfigurationError(w http.ResponseWriter, errorKind openapi.ErrorKindEnum, rsp_err error) {
	var result openapi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(openapi.Error); ok {
		result = rErr
	} else {
		result = openapi.NewError()
		err := result.FromJson(rsp_err.Error())
		if err != nil {
			result.Msg().Code = statusCode
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			result.Msg().Errors = []string{rsp_err.Error()}
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result); err != nil {
		log.Print(err.Error())
	}
}

/*
GetConfig: GET /api/config
Description: Gets the configuration resources.
*/
func (ctrl *bundlerController) GetConfig(w http.ResponseWriter, r *http.Request) {
	result, err := ctrl.handler.GetConfig(r)
	if err != nil {
		ctrl.responseGetConfigError(w, "internal", err)
		return
	}

	if result.HasPrefixConfig() {
		if _, err := httpapi.WriteJSONResponse(w, 200, result.PrefixConfig()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseGetConfigError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *bundlerController) responseGetConfigError(w http.ResponseWriter, errorKind openapi.ErrorKindEnum, rsp_err error) {
	var result openapi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(openapi.Error); ok {
		result = rErr
	} else {
		result = openapi.NewError()
		err := result.FromJson(rsp_err.Error())
		if err != nil {
			result.Msg().Code = statusCode
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			result.Msg().Errors = []string{rsp_err.Error()}
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result); err != nil {
		log.Print(err.Error())
	}
}
