// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
	"github.com/open-traffic-generator/openapiart/pkg"
)

type ApiTestController interface {
	Routes() []httpapi.Route
	/*
	GetRootResponse: GET /apitest
	Description: simple GET api with single return type
	*/
	GetRootResponse(w http.ResponseWriter, r *http.Request)
	/*
	PostRootResponse: POST /apitest
	Description: simple POST api with single return type
	*/
	PostRootResponse(w http.ResponseWriter, r *http.Request)
}

type ApiTestHandler interface {
	GetController() ApiTestController
	GetRootResponse(r *http.Request) openapiart.GetRootResponseResponse
	PostRootResponse(r *http.Request) openapiart.PostRootResponseResponse
}

