// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
	"github.com/open-traffic-generator/openapiart/pkg"
)

type BundlerController interface {
	Routes() []httpapi.Route
	/*
	SetConfig: POST /config
	Description: Sets configuration resources.
	*/
	SetConfig(w http.ResponseWriter, r *http.Request)
	/*
	UpdateConfig: PATCH /config
	Description: Sets configuration resources.
	*/
	UpdateConfig(w http.ResponseWriter, r *http.Request)
	/*
	GetConfig: GET /config
	Description: Gets the configuration resources.
	*/
	GetConfig(w http.ResponseWriter, r *http.Request)
}

type BundlerHandler interface {
	GetController() BundlerController
	SetConfig(r *http.Request) openapiart.SetConfigResponse
	UpdateConfig(r *http.Request) openapiart.UpdateConfigResponse
	GetConfig(r *http.Request) openapiart.GetConfigResponse
}

