// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
	"github.com/open-traffic-generator/openapiart/pkg"
)

type MetricsController interface {
	Routes() []httpapi.Route
	/*
	GetMetrics: GET /metrics
	Description: Gets metrics.
	*/
	GetMetrics(w http.ResponseWriter, r *http.Request)
	/*
	GetWarnings: GET /warnings
	Description: Gets warnings.
	*/
	GetWarnings(w http.ResponseWriter, r *http.Request)
	/*
	ClearWarnings: DELETE /warnings
	Description: Clears warnings.
	*/
	ClearWarnings(w http.ResponseWriter, r *http.Request)
}

type MetricsHandler interface {
	GetController() MetricsController
	GetMetrics(r *http.Request) openapiart.GetMetricsResponse
	GetWarnings(r *http.Request) openapiart.GetWarningsResponse
	ClearWarnings(r *http.Request) openapiart.ClearWarningsResponse
}

