// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"
	"github.com/open-traffic-generator/openapiart/pkg/httpapi"
	"github.com/open-traffic-generator/openapiart/pkg"
)

const (
	ServiceBItemId = "item_id"
	ServiceBLevel2 = "level_2"
)

type ServiceBController interface {
	Routes() []httpapi.Route
	/*
	GetAllItems: GET /serviceb
	Description: return list of some items
	*/
	GetAllItems(w http.ResponseWriter, r *http.Request)
	/*
	GetSingleItem: GET /serviceb/{item_id}
	Description: return single item
	*/
	GetSingleItem(w http.ResponseWriter, r *http.Request)
	/*
	GetSingleItemLevel2: GET /serviceb/{item_id}/{level_2}
	Description: return single item
	*/
	GetSingleItemLevel2(w http.ResponseWriter, r *http.Request)
}

type ServiceBHandler interface {
	GetController() ServiceBController
	GetAllItems(r *http.Request) openapiart.GetAllItemsResponse
	GetSingleItem(r *http.Request) openapiart.GetSingleItemResponse
	GetSingleItemLevel2(r *http.Request) openapiart.GetSingleItemLevel2Response
}

